service: box-video-skill-promise-donovan-24
provider:
  name: aws
  runtime: nodejs18.x
  environment:
      APIGATEWAY: 'ENTER_GENERATED_API_GATEWAY'
      S3_BUCKET: 'ENTER_GENERATED_S3_BUCKET_NAME'
      VI_ACCOUNT_ID: 'ENTER_VIDEO_INDEXER_ACCOUNT_ID'
      VI_AUTH_KEY_1: 'ENTER_AUTH_KEY1'
      VI_AUTH_KEY_2: 'ENTER_AUTH_KEY2'
      TEST_S3_BUCKET: 'randomtestbucket-donovan-aws-box-sbpd' # TESTING NEW FUNCTIONALITY
  timeout: 28
  
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*" 		

    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::randomtestbucket-donovan-aws-box-sbpd/*"

  iamManagedPolicies:
    # KMS Permissions
    - arn:aws:iam::755824957602:policy/KMS-Permissions
    # Secrets Manager Permissions
    - arn:aws:iam::755824957602:policy/Secrets-Manager-Access-Policy

functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: /
          method: any
    

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies