# dont forget to change the 'service' to your name
service: box-video-skill-
provider:
  name: aws
  runtime: nodejs14.x
  environment:
      APIGATEWAY: 'ENTER_GENERATED_API_GATEWAY'
      S3_BUCKET: 'ENTER_GENERATED_S3_BUCKET_NAME'
      VI_ACCOUNT_ID: 'ENTER_VIDEO_INDEXER_ACCOUNT_ID'
      VI_AUTH_KEY_1: 'ENTER_AUTH_KEY1'
      VI_AUTH_KEY_2: 'ENTER_AUTH_KEY2'
  timeout: 28
  
  
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"
  
functions:
  hello:
    handler: index.handler
    events:
      - http:
          path: /
          method: any

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies